# Generated by Django 5.1.2 on 2024-12-01 10:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                ("base_info", models.TextField(blank=True, max_length=3000, null=True)),
                (
                    "growth_habit",
                    models.TextField(blank=True, max_length=3000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Soil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soil_type", models.CharField(max_length=100)),
                ("moisture", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vermin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vermin_name", models.CharField(max_length=100)),
                ("base_info", models.TextField(blank=True, max_length=3000, null=True)),
                (
                    "suggested_measure",
                    models.TextField(blank=True, max_length=3000, null=True),
                ),
                ("image_url", models.URLField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserDefined",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sex", models.CharField(blank=True, max_length=10, null=True)),
                ("photo", models.URLField(blank=True, max_length=3000, null=True)),
                (
                    "birthday",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                ("current_drone", models.IntegerField(blank=True, null=True)),
                ("drone_total", models.IntegerField(blank=True, default=1, null=True)),
                ("identity", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "is_online",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drone_name",
                    models.CharField(
                        blank=True, default="无人机1号", max_length=100, null=True
                    ),
                ),
                (
                    "pro_date",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userdefined",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.IntegerField(blank=True, default=0, null=True)),
                ("content", models.TextField(blank=True, max_length=10000, null=True)),
                (
                    "post_date",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                ("post_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userdefined",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gen_date", models.DateField(default=datetime.date.today)),
                ("weather", models.TextField(blank=True, max_length=100, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("photo", models.URLField(blank=True, max_length=3000, null=True)),
                ("photo_record_method", models.IntegerField(blank=True, null=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.crop"
                    ),
                ),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.drone"
                    ),
                ),
                (
                    "soil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.soil"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userdefined",
                    ),
                ),
                (
                    "vermin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.vermin"
                    ),
                ),
            ],
        ),
    ]
