# Generated by Django 5.1.2 on 2024-12-01 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="post_time",
            field=models.TimeField(
                blank=True,
                default=datetime.datetime(2024, 12, 1, 20, 56, 26, 306684),
                null=True,
            ),
        ),
    ]
