# Generated by Django 5.1.2 on 2024-12-03 09:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_userpost_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="post_time",
            field=models.TimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.CreateModel(
            name="UserQuesSaved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userdefined",
                    ),
                ),
            ],
        ),
    ]
