# Generated by Django 5.1.2 on 2024-12-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_userpost_post_time_userquessaved"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquessaved",
            name="ai_answer",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="userquessaved",
            name="ques",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
